"""Production platform foundation: tenancy, identity, jobs, rules and connectors."""
from alembic import op
import sqlalchemy as sa
revision="20260822_03";down_revision="20260821_02";branch_labels=None;depends_on=None

def upgrade():
    for table in ("events","incidents","activity"):
        with op.batch_alter_table(table) as batch:
            batch.add_column(sa.Column("tenant_id",sa.String(),nullable=False,server_default="tenant-demo"));batch.create_index(f"ix_{table}_tenant_id",["tenant_id"])
    op.create_table("tenants",sa.Column("id",sa.String(),primary_key=True),sa.Column("name",sa.String(),nullable=False,unique=True),sa.Column("created_at",sa.DateTime(),nullable=False))
    op.create_table("user_accounts",sa.Column("id",sa.String(),primary_key=True),sa.Column("tenant_id",sa.String(),nullable=False,index=True),sa.Column("email",sa.String(),nullable=False,index=True),sa.Column("display_name",sa.String(),nullable=False),sa.Column("role",sa.String(),nullable=False,index=True),sa.Column("password_hash",sa.String(),nullable=False),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(),nullable=False),sa.UniqueConstraint("tenant_id","email",name="uq_user_tenant_email"))
    op.create_table("action_approvals",sa.Column("id",sa.String(),primary_key=True),sa.Column("tenant_id",sa.String(),nullable=False,index=True),sa.Column("incident_id",sa.String(),nullable=False,index=True),sa.Column("action",sa.String(),nullable=False),sa.Column("requested_by",sa.String(),nullable=False),sa.Column("approved_by",sa.String()),sa.Column("status",sa.String(),nullable=False,server_default="PENDING"),sa.Column("created_at",sa.DateTime(),nullable=False),sa.Column("decided_at",sa.DateTime()),sa.UniqueConstraint("tenant_id","incident_id","action","status",name="uq_open_action_approval"));op.create_index("ix_approval_tenant_status","action_approvals",["tenant_id","status"])
    op.create_table("ingestion_jobs",sa.Column("id",sa.String(),primary_key=True),sa.Column("tenant_id",sa.String(),nullable=False,index=True),sa.Column("idempotency_key",sa.String(),nullable=False),sa.Column("status",sa.String(),nullable=False,server_default="QUEUED"),sa.Column("event_count",sa.Integer(),nullable=False),sa.Column("attempts",sa.Integer(),nullable=False,server_default="0"),sa.Column("stream_id",sa.String()),sa.Column("error",sa.Text()),sa.Column("created_at",sa.DateTime(),nullable=False),sa.Column("updated_at",sa.DateTime(),nullable=False),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_job_tenant_idempotency"));op.create_index("ix_job_tenant_status","ingestion_jobs",["tenant_id","status"])
    op.create_table("detection_rules",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("rule_id",sa.String(),nullable=False,index=True),sa.Column("version",sa.String(),nullable=False),sa.Column("name",sa.String(),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("owner",sa.String(),nullable=False),sa.Column("severity",sa.String(),nullable=False),sa.Column("status",sa.String(),nullable=False,server_default="DRAFT"),sa.Column("enabled",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("parameters_json",sa.Text(),nullable=False,server_default="{}"),sa.Column("created_at",sa.DateTime(),nullable=False),sa.Column("promoted_at",sa.DateTime()),sa.UniqueConstraint("rule_id","version",name="uq_rule_version"));op.create_index("ix_rule_status","detection_rules",["status"])
    op.create_table("connector_executions",sa.Column("id",sa.String(),primary_key=True),sa.Column("tenant_id",sa.String(),nullable=False,index=True),sa.Column("incident_id",sa.String(),nullable=False,index=True),sa.Column("action",sa.String(),nullable=False),sa.Column("connector",sa.String(),nullable=False),sa.Column("idempotency_key",sa.String(),nullable=False),sa.Column("provider_request_id",sa.String()),sa.Column("status",sa.String(),nullable=False),sa.Column("dry_run",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("attempts",sa.Integer(),nullable=False,server_default="1"),sa.Column("detail",sa.Text(),nullable=False,server_default=""),sa.Column("created_at",sa.DateTime(),nullable=False),sa.UniqueConstraint("idempotency_key",name="uq_connector_idempotency"))

def downgrade():
    for table in ("connector_executions","detection_rules","ingestion_jobs","action_approvals","user_accounts","tenants"):op.drop_table(table)
